/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module \1bit  (
  input CLK,
  input D,
  input EN,
  output OUT
);
  wire OUT_temp;
  wire s0;
  wire s1;
  wire s2;
  assign s2 = ~ CLK;
  assign OUT_temp = ~ (~ (s0 & ~ s2) & ~ (OUT_temp & ~ (s1 & ~ s2)));
  assign s0 = ~ (~ (s2 & (D & EN)) & s1);
  assign s1 = ~ (s0 & ~ ((EN & ~ D) & s2));
  assign OUT = OUT_temp;
endmodule
